medical/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('medical_app.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medical_app/urls.py
from django.urls import path
from .views import *

urlpatterns = (
    path( '', medical_view, name = 'medical' ),
    path( 'medical/<int:id>/category', category_view, name = 'category' ),
    path( 'category/<int:id>/doctor', doctor_view, name = 'doctor' ),
    path( 'doctor/<int:id>/appointment', create_reserve, name = 'appointment' ),
)

medical_app/models.py
from django.db import models


class Medicallist( models.Model ):
    medical_name = models.CharField( max_length = 100 )

    def __str__(self):
        return f"{self.medical_name}"


class Category( models.Model ):
    med_id = models.ForeignKey( Medicallist, on_delete = models.CASCADE, null = True, blank = True )
    category_name = models.CharField( max_length = 100, null=True, blank=True )

    def __str__(self):
        return f"{self.med_id}, {self.category_name}"


class Doctor( models.Model ):
    category_id = models.ForeignKey( Category, on_delete = models.CASCADE, null = True, blank = True )
    name = models.CharField( max_length = 50 )
    surname = models.CharField( max_length = 50 )
    age = models.IntegerField( default = None )
    carrier = models.CharField( max_length = 1000 )
    picture = models.ImageField( upload_to = "post/",
                                 null = True, blank = True )

    def __str__(self):
        return f"{self.name}, {self.surname}, {self.age}, {self.carrier}, {self.picture}"

    """@property
    def short_name(self):
        return '{} {}.'.format( self.surname.title(), self.name[ 0 ].upper() )"""


class Reserve( models.Model ):
    unique_together = ('doctor', 'date', 'timeslot')

    TIMESLOT_LIST = (
        (0, '09:00 – 10:00'),
        (1, '10:00 – 11:00'),
        (2, '11:00 – 12:00'),
        (3, '12:00 – 13:00'),
        (4, '13:00 – 14:00'),
        (5, '14:00 – 15:00'),
        (6, '15:00 – 16:00'),
        (7, '16:00 – 17:00'),
        (8, '17:00 – 18:00'),
    )

    doctor = models.ForeignKey( Doctor, on_delete = models.CASCADE )
    name = models.CharField( max_length = 50 )
    surname = models.CharField( max_length = 50 )
    age = models.IntegerField( default = None )
    date = models.DateField()
    timeslot = models.IntegerField( choices = TIMESLOT_LIST )
    contact_number = models.CharField( max_length = 15 )
    comment = models.CharField( max_length = 1000 )

    def __str__(self):
        return f"{self.name}, {self.surname}, {self.age}, {self.date}, {self.timeslot}, {self.comment}"

    """#@property
    def time(self):
        return self.TIMESLOT_LIST[ self.timeslot ][ 1 ]"""

medical_app/forms.py
from datetime import date

from django import forms
from datetimewidget.widgets import DateTimeWidget
from .models import *


class MedicalForm(forms.ModelForm):
    class Meta:
        model = Medicallist
        fields = ['medical_name']

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category_name']



class ReserveForm(forms.ModelForm):
    class Meta:
        model = Reserve
        fields = ['doctor', 'name', 'surname','comment',
                  'age', 'date', 'timeslot', 'contact_number']
        
    
        


        #widgets = {
        #     'date': DateTimeWidget(
        #         attrs={'id': 'date'}, usel10n=False, bootstrap_version=3,
        #         options={
        #             'minView': 2,  
        #             'maxView': 3,  
        #             'weekStart': 1,
        #             'todayHighlight': True,
        #             'format': 'yyyy-mm-dd',
        #             'daysOfWeekDisabled': [0, 6],
        #             'startDate': date.today().strftime('%Y-%m-%d'),
        #         }),
        # }
    
    # def clean_date(self):
    #     day = self.cleaned_data['date']

    #     if day <= date.today():
    #         raise forms.ValidationError('Date should be upcoming (tomorrow or later)', code='invalid')
    #     if day.isoweekday() in (0, 6):
    #         raise forms.ValidationError('Date should be a workday', code='invalid')

    #     return day

medical_app/views.py
from django.http import Http404
from django.shortcuts import render, get_list_or_404, redirect
from .models import  Medicallist, Category, Reserve
from .forms import *


def medical_view(request):
    context = {}
    context["medicals"] = Medicallist.objects.all()
    return render(request, 'medicallist.html', context)

def category_view(request, id):
    context = {}
    try:
        context['category'] = Category.objects.filter(med_id__pk=id)
    except Category.DoesNotExist:
        raise Http404
    return render(request, 'category_list.html', context)

def doctor_view(request, id):
    context = {}
    context['doctor'] = Doctor.objects.filter(category_id__pk=id)
    return render(request, 'doctor_list.html', context)

def create_reserve(request, id):
    context = {}
    form = ReserveForm(request.POST or None)
    date = request.POST.get("date")
    timeslot = request.POST.get("timeslot")
    if Reserve.objects.filter(date=date,timeslot=timeslot):
        return redirect("create_reserve")
    if form.is_valid():
        form.save()
        return redirect('medical_view')
    context['form'] = form
    return render(request, 'reserve.html', context)

medical_app/templates/category_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>DirectoryAds &mdash; Colorlib Website Template</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'medical/fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{% static 'medical/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'medical/css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'medical/css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'medical/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'medical/css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'medical/css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'medical/fonts/flaticon/font/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'medical/css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'medical/css/rangeslider.css' %}">
  <link rel="stylesheet" href="{% static 'medical/css/style.css' %}">
</head>
<body>
<div id="back-1">
  <div class="site-wrap">
    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    <header class="site-navbar container py-0 " role="banner">
      <div class="row align-items-center">
        <div class="d-inline-block d-xl-none ml-auto py-3 col-6 text-right" style="position: relative; top: 3px;">
          <a href="#" class="site-menu-toggle js-menu-toggle text-white"><span class="icon-menu h3"></span></a>
        </div>
      </div>
    </header>
    <div class="site-blocks-cover overlay" style="background-image: url(images/729_486_5a3a67b3d801d.jpg);"
      data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center justify-content-center text-center">
          <div class="col-md-12">
            <div class="row justify-content-center mb-4">
              <div class="col-md-8 text-center">
                <h1 class="" data-aos="fade-up">Welcome To DirectoryAds</h1>
                <p data-aos="fade-up" data-aos-delay="100">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                </p>
              </div>
            </div>
            <div class="form-search-wrap mb-3" data-aos="fade-up" data-aos-delay="200">
              <form method="post">
                <div class="row align-items-center">
                  <div class="col-lg-12 mb-4 mb-xl-0 col-xl-3">
                  </div>
                  <div class="col-lg-12 mb-4 mb-xl-0 col-xl-3">
                    <div class="select-wrap">
                      <img class="img" src="../../static/medical/images/down-arrow.png">
                      <select class="form-control rounded bas" name="" id="cnt">
                      {% for cat in category %}
                        <option value="{% url 'doctor' id=cat.id %}">{{ cat.category_name }}</option>
                      {% endfor %}
                      </select>
                    </div>
                  </div>
                  <a class="link" href="#" id="btn-one">Link</a>
                </div>                
            </div>
          </div>
        </div>
      </div>
    </div>
    </form>
  </div>
</div>
  <script src="{% static 'medical/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery-ui.js' %}"></script>
  <script src="{% static 'medical/js/popper.min.js' %}"></script>
  <script src="{% static 'medical/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'medical/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'medical/js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'medical/js/aos.js' %}"></script>
  <script src="{% static 'medical/js/rangeslider.min.js' %}"></script>
  <script src="{% static 'medical/js/main.js' %}"></script>
</body>
</html>

medical_app/templates/doctor_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>DirectoryAds &mdash; Colorlib Website Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'medical/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'medical/fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/rangeslider.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/index_2ciseyfe.css' %}">
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  </head>
  <body>
  <style>
    #btn {
      width: 100%;
      border-bottom-left-radius: 31.8px;
      border-bottom-right-radius: 31.8px;
    }

    #btn:focus {
      border:none;
      outline: none;
    }
  </style>
  <div id="qwerty" class="site-wrap">
    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    <div style="background: url('/static/medical/images/find-a-doc-group.jpg'); background-repeat: no-repeat;background-size: cover;" class="site-blocks-cover inner-page-cover overlay" data-aos="fade" data-stellar-background-ratio="0.5">
      <div class="container">
        <div class="row align-items-center justify-content-center text-center">
          <div class="col-md-10" data-aos="fade-up" data-aos-delay="400">
            <div class="row justify-content-center mt-5">
              <div class="col-md-8 text-center">
                <h1 class="basliq-1">Hekimlerin Siyahisi</h1>
                <p class="mb-0">...</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
      <div class="cnt-1 container-fluid">
        <hr>
          <div class="row">
    {% for doc in doctor %}  

            <div class="col-md-3">
                  <a href="{% url 'appointment' doc.id %}">
                    <img style="width:100%;"  src={{doc.picture.url}}>
                  </a>
                  <div class="txt-1">
                    <p id="demo">{{ doc.name}} {{ doc.surname}} 
                    {{ doc.age}} {{ doc.carrier}}                    
                  </p>
                <button id="btn">Haqqinda</button>
                </div>
          </div>
          {% endfor %}

        </div>
    
    </div>
        </div>   
        <footer>
          <div class="container">
            <div class="row">
              <div class="col-md-3">
                <div class="foot">
                </div>
              </div>
            </div>
          </div>
        </footer>
<script>
    $( "#btn" ).click(function() {
        $(this).siblings('p').slideToggle();
      })

    $( "#btn-1" ).click(function() {
        $(this).siblings('p').slideToggle( "slow" );
      })
    $("#btn-2").click(function(){
      $(this).siblings('p').slideToggle("slow")
    })
    $("#btn-3").click(function(){
      $(this).siblings('p').slideToggle("slow")
    })
    
</script>
  <script src="{% static 'medical/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery-ui.js' %}"></script>
  <script src="{% static 'medical/js/popper.min.js' %}"></script>
  <script src="{% static 'medical/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'medical/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'medical/js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'medical/js/aos.js' %}"></script>
  <script src="{% static 'medical/js/rangeslider.min.js' %}"></script>
  <script src="{% static 'medical/js/main.js' %}"></script>
  </body>
</html>

medical_app/templates/medicallist.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <title>Medical App</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'medical/fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/jquery-ui.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/bootstrap-datepicker.css' %}">
    <link rel="stylesheet" href="{% static 'medical/fonts/flaticon/font/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/rangeslider.css' %}">
    <link rel="stylesheet" href="{% static 'medical/css/style.css' %}">
  </head>
  <body>
  <div class="site-wrap">
    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>
    <header class="site-navbar container py-0 " role="banner">
        <div class="row align-items-center">
          <div class="d-inline-block d-xl-none ml-auto py-3 col-6 text-right" style="position: relative; top: 3px;">
            <a href="#" class="site-menu-toggle js-menu-toggle text-white"><span class="icon-menu h3"></span></a>
          </div>
        </div>
    </header>
    <div id="background" class="site-blocks-cover overlay">
      <div class="container">
        <div class="row align-items-center justify-content-center text-center">
          <div class="col-md-12">
            <div class="row justify-content-center mb-4">
              <div class="col-md-8 text-center">
                <h1 class="" data-aos="fade-up">WELCOME</h1>
                <p data-aos="fade-up" data-aos-delay="100">...</p>
              </div>
            </div>
            <div class="form-search-wrap mb-3" data-aos="fade-up" data-aos-delay="200">
                <a class="lnk" href="#">Link</a>
                {% csrf_token %}
                <div class="row align-items-center">
                  <div class="col-lg-12 mb-4 mb-xl-0 col-xl-3">
                    <div class="select-wrap">
                      <select class="form-control rounded" name="" id="xest">
                      <img class="img" src="../../static/medical/images/down-arrow.png">
                      {% for med in medicals %}
                        <option value="{% url 'category' id=med.id %}" >{{med.medical_name}}</option>
                      {% endfor %}
                      </select>
                    </div>
                  </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>                     
  <script src="{% static 'medical/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery-ui.js' %}"></script>
  <script src="{% static 'medical/js/popper.min.js' %}"></script>
  <script src="{% static 'medical/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'medical/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'medical/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'medical/js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'medical/js/aos.js' %}"></script>
  <script src="{% static 'medical/js/rangeslider.min.js' %}"></script>
  <script src="{% static 'medical/js/main.js' %}"></script>
  </body>
</html>

medical_app/templates/reserve.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>DirectoryAds &mdash; Colorlib Website Template</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'directoryads/fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/css/magnific-popup.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/fonts/flaticon/font/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/css/rangeslider.css' %}">
  <link rel="stylesheet" href="{% static 'directoryads/css/add.css' %}">
</head>
<body>
  <style>
    #id_doctor {
      width: 78%;
      margin-left: 3.4em;
      height: 2em;
    }

    #id_timeslot {
      margin-left: 3.3em;
      width: 78%;
      height: 2em;
      margin-top: 0.5em;
    }

    #id_name {
      height: 2em;
      margin-top: 0.8em;
    }

    #id_surname {
      height: 2em;
      margin-top: 1em;
    }

    #id_age {
      height: 2em;
      margin-top: 1em;
    }

    #id_comment {
      height: 2em;
      margin-top: 1em;
    }

    #id_date {
    margin-left: 3em;
    margin-top: 1em;
    width: 78%;
    height: 35px;
    border-top-left-radius: 4px;
    border-top-right-radius: 4px;
    border-bottom-left-radius: 4px;
    border-bottom-right-radius: 4px;
    }

    #id_contact_number {
      height: 2em;
      margin-top: 1em;
    }

      
    
  </style>
  <header>
    <div id="back" class="container-fluid">
      <form>
      {% csrf_token %}
      {{ form.non_field_errors }}

      {% for hidden_field in form.hidden_fields %} placeholder="utuyt"
      {{ hidden_field.errors }}
      {{ hidden_field }}
      {% endfor %}

      
        <div class="dws-input">
        {% for field in form.visible_fields %}
         <p>
          {{ field }}
         {{ field.errors }}
         </p>
        {% endfor %}
          {% comment %} <input type="text" name="username" placeholder="Adinizi daxil edin...">
          <input style="width: 78%; margin-left: 3.4em; height: 3em;" id="date" type="date" name="rezerv"
            placeholder="Rezerv gununu qeyd edin...">
          <input type="text-one" name="surname" placeholder="Soyadinizi daxil edin...">
          <input type="number" name="age" placeholder="Yasinizi daxil edin...">
          <input type="number-one" name="number" placeholder="Nomrenizi daxil edin...">
          <input type="text-two" name="email" placeholder="Email daxil edin..."> {% endcomment %}
          <button id="btn" type="submit">Gonder</button>
        </div>
      </form>
    </div>
  </header>
  <script src="{% static 'directoryads/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'directoryads/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'directoryads/js/jquery-ui.js' %}"></script>
  <script src="{% static 'directoryads/js/popper.min.js' %}"></script>
  <script src="{% static 'directoryads/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'directoryads/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'directoryads/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'directoryads/js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'directoryads/js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'directoryads/js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'directoryads/js/aos.js' %}"></script>
  <script src="{% static 'directoryads/js/rangeslider.min.js' %}"></script>
  <script src="{% static 'directoryads/js/main.js' %}"></script>
  
  
  <script>
    $("#btn").click(function (ev) {
      ev.preventDefault()
      alert('Melumat Gonderildi Rezerv elediyiniz Hekime. Siznen Elaqe Saxliyacaglar.');
    })
  </script>
</body>
</html>